# Generated by Django 3.2.3 on 2021-06-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='done',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Doing', 'Doing'), ('Done', 'Done')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
